defmodule ClienttCrmApp.Repo.Migrations.RenameFormsTablesAndAddCompanyIdToFields do
  @moduledoc """
  Renames Forms domain tables and adds company_id to forms_fields.

  This file was modified from the autogenerated migration to use RENAME
  operations instead of creating new tables.
  """

  use Ecto.Migration

  def up do
    # 1. Drop foreign key constraints that reference the old table names
    drop constraint(:form_fields, "form_fields_form_id_fkey")
    drop constraint(:submissions, "submissions_form_id_fkey")

    # 2. Rename tables
    rename table(:forms), to: table(:forms_forms)
    rename table(:form_fields), to: table(:forms_fields)
    rename table(:submissions), to: table(:forms_submissions)

    # 3. Add company_id to forms_fields (nullable first)
    alter table(:forms_fields) do
      add :company_id, :uuid
    end

    # 4. Populate company_id from parent form
    execute """
    UPDATE forms_fields
    SET company_id = forms_forms.company_id
    FROM forms_forms
    WHERE forms_fields.form_id = forms_forms.id
    """

    # 5. Make company_id NOT NULL and add foreign key constraint
    alter table(:forms_fields) do
      modify :company_id, :uuid, null: false
    end

    alter table(:forms_fields) do
      modify :company_id,
             references(:authz_companies,
               column: :id,
               name: "forms_fields_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    # 6. Recreate foreign key constraints with new table names
    alter table(:forms_fields) do
      modify :form_id,
             references(:forms_forms,
               column: :id,
               name: "forms_fields_form_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:forms_submissions) do
      modify :form_id,
             references(:forms_forms,
               column: :id,
               name: "forms_submissions_form_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    # 7. Rename unique indexes
    execute "ALTER INDEX forms_unique_name_per_company_index RENAME TO forms_forms_unique_name_per_company_index"
    execute "ALTER INDEX forms_unique_slug_per_company_index RENAME TO forms_forms_unique_slug_per_company_index"
  end

  def down do
    # 1. Rename unique indexes back
    execute "ALTER INDEX forms_forms_unique_name_per_company_index RENAME TO forms_unique_name_per_company_index"
    execute "ALTER INDEX forms_forms_unique_slug_per_company_index RENAME TO forms_unique_slug_per_company_index"

    # 2. Drop foreign key constraints
    drop constraint(:forms_submissions, "forms_submissions_form_id_fkey")
    drop constraint(:forms_fields, "forms_fields_form_id_fkey")
    drop constraint(:forms_fields, "forms_fields_company_id_fkey")

    # 3. Remove company_id from forms_fields
    alter table(:forms_fields) do
      remove :company_id
    end

    # 4. Rename tables back to original names
    rename table(:forms_submissions), to: table(:submissions)
    rename table(:forms_fields), to: table(:form_fields)
    rename table(:forms_forms), to: table(:forms)

    # 5. Recreate original foreign key constraints
    alter table(:form_fields) do
      modify :form_id,
             references(:forms,
               column: :id,
               name: "form_fields_form_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:submissions) do
      modify :form_id,
             references(:forms,
               column: :id,
               name: "submissions_form_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
