defmodule ClienttCrmApp.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:authz_teams, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:authz_users) do
      modify :team_id,
             references(:authz_teams,
               column: :id,
               name: "authz_users_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:authz_users, [:team_id])

    alter table(:authz_teams) do
      add :company_id,
          references(:authz_companies,
            column: :id,
            name: "authz_teams_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :name, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "active"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:authz_teams, [:company_id, :name],
             name: "authz_teams_unique_name_per_company_index"
           )

    create table(:authz_company_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :company_id,
          references(:authz_companies,
            column: :id,
            name: "authz_company_settings_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :max_users, :bigint
      add :max_teams, :bigint
      add :features, :map, null: false, default: %{}
      add :branding, :map, null: false
      add :timezone, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:authz_company_settings, [:company_id],
             name: "authz_company_settings_unique_company_index"
           )
  end

  def down do
    drop_if_exists unique_index(:authz_company_settings, [:company_id],
                     name: "authz_company_settings_unique_company_index"
                   )

    drop constraint(:authz_company_settings, "authz_company_settings_company_id_fkey")

    drop table(:authz_company_settings)

    drop_if_exists unique_index(:authz_teams, [:company_id, :name],
                     name: "authz_teams_unique_name_per_company_index"
                   )

    drop constraint(:authz_teams, "authz_teams_company_id_fkey")

    alter table(:authz_teams) do
      remove :updated_at
      remove :created_at
      remove :status
      remove :description
      remove :name
      remove :company_id
    end

    drop_if_exists index(:authz_users, [:team_id])

    drop constraint(:authz_users, "authz_users_team_id_fkey")

    alter table(:authz_users) do
      modify :team_id, :uuid
    end

    drop table(:authz_teams)
  end
end
