defmodule ClienttCrmApp.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:authz_users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :authn_user_id,
          references(:users,
            column: :id,
            name: "authz_users_authn_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :company_id, :uuid, null: false
      add :role, :text, null: false
      add :team_id, :uuid
      add :team_role, :text
      add :status, :text, null: false, default: "active"
      add :display_name, :text
      add :joined_at, :utc_datetime_usec, null: false
      add :last_active_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:authz_companies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:authz_users) do
      modify :company_id,
             references(:authz_companies,
               column: :id,
               name: "authz_users_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:authz_users, [:authn_user_id, :company_id],
             name: "authz_users_unique_user_company_index"
           )

    alter table(:authz_companies) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :status, :text, null: false, default: "active"
      add :settings_id, :uuid

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:authz_companies, [:slug], name: "authz_companies_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:authz_companies, [:slug],
                     name: "authz_companies_unique_slug_index"
                   )

    alter table(:authz_companies) do
      remove :updated_at
      remove :created_at
      remove :settings_id
      remove :status
      remove :slug
      remove :name
    end

    drop_if_exists unique_index(:authz_users, [:authn_user_id, :company_id],
                     name: "authz_users_unique_user_company_index"
                   )

    drop constraint(:authz_users, "authz_users_company_id_fkey")

    alter table(:authz_users) do
      modify :company_id, :uuid
    end

    drop table(:authz_companies)

    drop constraint(:authz_users, "authz_users_authn_user_id_fkey")

    drop table(:authz_users)
  end
end
