defmodule ClienttCrmApp.Repo.Migrations.RenameUsersToAuthnUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Drop the foreign key constraint from authz_users
    drop constraint(:authz_users, "authz_users_authn_user_id_fkey")

    # Rename the users table to authn_users
    rename table(:users), to: table(:authn_users)

    # Recreate the foreign key constraint with the new table name
    alter table(:authz_users) do
      modify :authn_user_id,
             references(:authn_users,
               column: :id,
               name: "authz_users_authn_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    # Rename the unique index
    execute "ALTER INDEX users_unique_email_index RENAME TO authn_users_unique_email_index"
  end

  def down do
    # Rename the unique index back
    execute "ALTER INDEX authn_users_unique_email_index RENAME TO users_unique_email_index"

    # Drop the foreign key constraint
    drop constraint(:authz_users, "authz_users_authn_user_id_fkey")

    # Rename the table back to users
    rename table(:authn_users), to: table(:users)

    # Recreate the foreign key constraint with the original table name
    alter table(:authz_users) do
      modify :authn_user_id,
             references(:users,
               column: :id,
               name: "authz_users_authn_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
